global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  
  - job_name: 'hotel-service'
    static_configs:
      - targets: ['hotel-service:3001']
  
  - job_name: 'trip-service'
    static_configs:
      - targets: ['trip-service:3002']
  
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3003']
  
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3004']