apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: travel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: hotel-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/hoteldb"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: travel-booking
spec:
  selector:
    app: hotel-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP